stages:
  - lint
  - assume-role
  - deploy

variables:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: argus
  ECS_SERVICE: argus-service
  ECS_CLUSTER: eep-staging
  ECS_TASK_DEFINITION: argus-task-staging
  CONTAINER_NAME: argus
  AWS_ACCOUNT_ID: 891377379277
  ROLE_TO_ASSUME: arn:aws:iam::891377379277:role/GitlabCI

lint:
  stage: lint
  image: node:latest
  script:
    - npm install
    - npm install -g aws-cli
    - npm run lint

assume-role:
  stage: assume-role
  image: 
    name: amazon/aws-cli:latest
    entrypoint: [""]
  id_tokens:
    MY_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    - mkdir -p ~/.aws
    - echo "${MY_OIDC_TOKEN}" > /tmp/web_identity_token
    - echo -e "[profile oidc]\nrole_arn=${ROLE_TO_ASSUME}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config
  script:
    - echo "Configuring AWS credentials..."
    - aws sts get-caller-identity

deploy:
  stage: deploy
  image: amazon/aws-cli
  services:
    - docker:dind
  script:
    - export AWS_ROLE_ARN=$ROLE_TO_ASSUME
    - export AWS_WEB_IDENTITY_TOKEN_FILE=/root/.aws/token.jwt
    - export AWS_DEFAULT_REGION=$AWS_REGION
    - aws sts assume-role-with-web-identity --role-arn $AWS_ROLE_ARN --role-session-name GitLabCI --web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE > /tmp/credentials
    - export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' /tmp/credentials)
    - export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' /tmp/credentials)
    - export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' /tmp/credentials)

    - echo "Logging into Amazon ECR..."
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

    - echo "Building and pushing Docker image..."
    - export IMAGE_TAG=$(git rev-parse HEAD)
    - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
    - docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

    - echo "Updating ECS Task Definition..."
    - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment